name = "server"
main = "src/index.ts"
compatibility_date = "2024-11-21"

# compatibility_flags = [ "nodejs_compat" ]

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiOTViZTk0NjMtNTU2Zi00Zjc0LTk2MTgtYzU4NWRjMzEyNjZiIiwidGVuYW50X2lkIjoiN2VlYWQ0ZDJhMDRkMDc1ODNkZmMxY2Y2ODE1NzBmODliZGQxNWI2ODFhZjQ5Y2JkN2I3NzY4N2MzMzA3MzAyNiIsImludGVybmFsX3NlY3JldCI6IjQ5YzZkZjM1LTJjMjctNGU2NS1iODI5LTJmMWNjYmU1ODRmOCJ9.REGOQxQIBZfyAEUSEEyWrfc_wdKhWfA5iqehezMZIwQ"
